# Generated by Django 4.2.9 on 2024-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ainomic_blog', '0002_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
